### PR TITLE
Compatibility with commonmark v23 spec

### PR DESCRIPTION
**Pull request by nikolas**
This branch started by following this commonmark.js commit:
https://github.com/jgm/commonmark.js/commit/f3dace328901bba712b8458e5ad329a038663771
Where linked lists were introduced to the node structure.

I soon realized these structural changes required me to port lots of the new code from commonmark.js.

I've refactored the main parser and rendering code in blocks.py, inlines.py, and html.py.

### CODE REVIEW

**Comment by nikolas** [comment]
Alright so this branch is down to 5 test failures now, I'm still working on this.

Now, an important note is that this giant change pretty much rewrites the entire parser and renderer. It removes the ExtensionBlock additions from @lu-zero. My thinking was that those additions can be rewritten on top of this new code. In order to keep maintenance simple, it would be nice if those additions could be contained in a separate file, like `extensions.py`, so the core commonmark code remains in sync with the `commonmark.js` reference implementation.

One way forward that I was thinking of: when these changes are done, we release version 0.6.0 of this library, with a note that if you're using Luca's extensions, you'll need to stay at version 0.5.5 for now, until we implement those features again.

This is just an idea.. basically because I don't feel comfortable implementing those features myself since I don't know the use case or the spec: it's very straightforward to develop against the commonmark spec, but more complicated to introduce changes to that spec that are less understood.

**Comment by ericholscher** [comment]
I generally agree we should be sticking to the spec, and having optional extensions be separated out from the core. Currently the spec doesn't define an extension mechanism, but perhaps that is the best way to move forward with this. Then non-spec additions could be added as extensions (either shipped with the project itself, or developed by third party authors).

I think the main bit of work around that would be figuring out the best way to handle extensions. I haven't looked at this PR in depth, but in general that's my thinking around non-standard additions.

**Comment by lu-zero** [comment]
I do not have time to check how markdown-it but I'd try to stay as compatible as possible with it.

**Comment by lu-zero** [comment]
That said the extension block can be dropped if @ericholscher is not using it.

**Comment by nikolas** [comment]
markdown-it has a directory of fixtures that we can use to validate our compatibility: https://github.com/markdown-it/markdown-it/tree/master/test/fixtures/markdown-it

We can use these files to implement these features.

**Comment by ericholscher** [comment]
I don't believe we're using the ExtensionBlock currently -- we experimented with it, but ended up not using it yet.

**Comment by lu-zero** [comment]
Then it is good to go I guess =)

**Pull request merged**
