### PR TITLE
Update to commonmark spec 0.25

### LINKED ISSUE #58: Update to version 0.25 of the CommonMark spec
http://spec.commonmark.org/0.25/

### PR DESCRIPTION
**Pull request by nikolas**
Closes #58

### CODE REVIEW

**Comment by nikolas** [comment]
@ericholscher or @lu-zero - please look over this when you have a chance, thanks.

**Comment by lu-zero** [comment]
the commits seems to have many changes that might be grouped differently, not against taking it as is though.

BTW shall we move to `commonmark` instead of CommonMark internally first?

**Comment by nikolas** [comment]
The move from `CommonMark` to `commonmark` can be done at any time. That's going to be tricky and I don't really know how to do that. Do we rename the `CommonMark` dir to `commonmark`? Provide a symlink from `CommonMark` to `commonmark`? Either way, that change isn't related to updating the spec.

Regarding the grouping of the commits, I could put these changes all in one commit instead of two, but it would be difficult to split them out into more commits.

**Comment by nikolas** [comment]
I'd like to merge this and make a new release - if there's any objections let me know. I'll try and keep my git history cleaner in the future. If I'm working towards a specific functionality like a new version of the spec, I tend to lump everything in one commit.. but I can try to change that.

**Pull request merged**
