### PR TITLE
Fix json AST output

### LINKED ISSUE #76: Understanding of JSON output
Hi all,

I try to get JSON output using this library.

I tried the Python library and the cmark command line tool with the same results. HTML and AST looks ok for me:

```bash
cmark  <<< '*hello!*'
```
```html
<p><em>hello!</em></p>
```
```bash
cmark -a <<< '*hello!*'
```
```
[document]
	Title:
	Info:
	Destination:
	Sourcepos: [[1, 1], [1, 8]]
	Info:
	Literal:
	Children:
		-> [document]
			-> Title:
			-> Info:
...
```

But I do not understand the JSON output:

```bash
cmark -aj <<< '*hello!*'
```
```json
{"is_fenced": false, "t": "document", "sourcepos": [[1, 1], [1, 8]], "fence_length": 0, "open": false, "last_line_blank": false}
```

Honestly, I have no idea what this all about...

I expect some like this:

```json
[ "paragraph" , [
  [ "emph" , {} , [
    [ "text" , {} , [ "hello"
...
```

Can you give me some hints what I am oing wrong?

Regards,
Reto

### PR DESCRIPTION
**Pull request by nikolas**
Closes #76

### CODE REVIEW

**Comment by lu-zero** [comment]
why changing the method name?

**Comment by nikolas** [comment]
So it matches the other method which is similar: `dumpAST`. If you think I should leave it `ASTtoJSON` I'll change it back, though.

**Comment by lu-zero** [comment]
Not sure how many users would break with that change.

Given it is a fringe part of the api probably would be ok either way @ericholscher what do you think?

**Comment by nikolas** [comment]
The `ASTtoJSON` function was completely broken anyways, as noted in issue #76.. so I don't think anyone was using it.

**Comment by lu-zero** [comment]
Then it is good as is =)

**Pull request merged**
