### PR TITLE
Add a changelog

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by lu-zero** [comment]
I'm not against it but would be good this way or just generate it from git logs (yes, that requires formatted commit messages) ?

**Comment by nikolas** [comment]
Hmm.. sure if you want to set that up. I've always just used manually written changelogs, since not every detail is relevant to users. I assume that could be automated as well, though, with some commit message format.

**Comment by lu-zero** [comment]
Let's keep it simple, the other @rtfd projects do not use that machinery either.

**Comment by ericholscher** [comment]
Yea, I'm generally +1 on hand written changelogs. They can link to
issues/commits for more clarity, but in general commit messages don't have
a 1-to-1- mapping to what should appear in the change log.

On Sun, Jan 3, 2016 at 8:49 AM, Luca Barbato <notifications@github.com>
wrote:

> Merged #36 <https://github.com/rtfd/CommonMark-py/pull/36>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/CommonMark-py/pull/36#event-504235123>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Pull request merged**
