### PR TITLE
Port more changes from commonmark.js

### PR DESCRIPTION
**Pull request by nikolas**
In this PR:
* Split main code out into parts: blocks.py, inlines.py, node.py, html.py
* Updated some of the regexes, which keeps tests passing on our current spec, while reducing some of the failures with the latest commonmark spec
* Rename some of the internal structures based on the changes from the past year in commonmark.js, e.g. `DocParser` -> `Parser`, `ListItem` -> `Item`.

### CODE REVIEW

**Comment by lu-zero** [comment]
What's wrong with the tests?

**Comment by nikolas** [comment]
Woops - i forgot to rename some things in bin/cmark.py, i'll fix it.

**Comment by ericholscher** [comment]
This looks great! I haven't reviewed it too well, but the tests pass, and in general having multiple files is much better in my book.

**Comment by lu-zero** [comment]
+1

**Pull request merged**
