### PR TITLE
Cleanup / test fixes with new spec

### PR DESCRIPTION
**Pull request by nikolas**
I've removed the ExtensionBlock code I saw Luca was working
on. This is because, when running the tests on the CommonMark
0.22 spec, I get 157 failures with the ExtensionBlock code in,
and 129 failures without. So I thought that for now we can leave
it out.

### CODE REVIEW

**Comment by lu-zero** [comment]
I wouldn't remove it if it isn't strictly necessary, I'm afraid recommonmark and related code relies on it.

**Comment by nikolas** [comment]
Alright, thanks for letting me know. I'll add back in the extension block stuff to this PR. We can address the issue later if necessary.

**Comment by nikolas** [comment]
I've updated this PR - I've left ExtensionBlock alone.

**Comment by lu-zero** [comment]
Thanks a lot!

**Pull request merged**
